plugins {
    id 'org.springframework.boot' version "${springBootVersion}" apply false
    id 'io.spring.dependency-management' version "${springDependencyManagementVersion}" apply false
}

allprojects {
    group = 'umlerr'
    version = '1.0-SNAPSHOT'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java-library'
    apply plugin: 'checkstyle'
    apply plugin: 'pmd'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
    }

    checkstyle {
        configFile = rootProject.file('config/checkstyle/checkstyle.xml')
        maxWarnings = 0
    }

    pmd {
        ruleSets = []
        ruleSetFiles = files("${rootDir}/config/pmd/pmd.xml")
    }
}
